### ISSUE TITLE
Testnets?

### ISSUE THREAD

**Issue by mktcode** [ensdomains/ens-subgraph#41]
Any chance to get this deployed for let's say rinkeby, other than... doing it myself, "unofficially"? 😃

**Comment by Arachnid** [comment]
Already done:
 - https://thegraph.com/hosted-service/subgraph/ensdomains/ensrinkeby
 - https://thegraph.com/hosted-service/subgraph/ensdomains/ensgoerli
 - https://thegraph.com/hosted-service/subgraph/ensdomains/ensropsten
